version: 2
updates:
  # 1. Vérification des dépendances npm (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Africa/Douala"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Regroupe les petites mises à jour mineures/patchs dans une seule PR
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2. Vérification des actions GitHub (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Africa/Douala"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci(deps)"